# Generated by Django 3.2 on 2022-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220721_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
