# Generated by Django 3.2 on 2022-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_batch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
