# Generated by Django 3.2 on 2022-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220722_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hsc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
