# Generated by Django 3.2 on 2022-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='courses',
            field=models.ManyToManyField(to='academic.Course'),
        ),
    ]
