# Generated by Django 3.2 on 2022-07-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220722_1112'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.batch'),
        ),
        migrations.AlterField(
            model_name='result',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course'),
        ),
    ]
