# Generated by Django 3.2 on 2022-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_exam_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='name',
        ),
        migrations.AddField(
            model_name='result',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
