# Generated by Django 3.2 on 2022-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20220616_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='is_availabe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_discount_available',
            field=models.BooleanField(default=False),
        ),
    ]
